# Generated by Django 5.1.2 on 2025-05-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
