# Generated by Django 5.1.2 on 2025-05-25 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Ikeja Electric', 'Ikeja Electric'), ('Eko Disco', 'Eko Disco'), ('Abuja Disco', 'Abuja Disco')], help_text='Electricity service provider.', max_length=50)),
                ('meter_number', models.CharField(help_text='Meter number for the electricity payment.', max_length=20)),
                ('meter_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], help_text='Type of meter (prepaid/postpaid).', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid for electricity.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', help_text='Current status of the payment.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the payment was created.')),
                ('user', models.ForeignKey(help_text='User who made the payment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electricity Payment',
                'verbose_name_plural': 'Electricity Payments',
            },
        ),
        migrations.CreateModel(
            name='TVSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('DSTV', 'DSTV'), ('GOTV', 'GOTV'), ('Startimes', 'Startimes')], help_text='TV service provider.', max_length=20)),
                ('smart_card_number', models.CharField(help_text='Smart card number for the TV subscription.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid for the subscription.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', help_text='Current status of the payment.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the payment was created.')),
                ('user', models.ForeignKey(help_text='User who made the subscription.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TV Subscription',
                'verbose_name_plural': 'TV Subscriptions',
            },
        ),
    ]
