# Generated by Django 5.1.2 on 2025-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the sender', max_length=250)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated unique identifier for URL usage')),
                ('email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('content', models.TextField(help_text='Message content')),
                ('read', models.BooleanField(default=False, help_text='Indicates if the message has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was created', null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
