# Generated by Django 5.1.2 on 2025-05-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=350)),
                ('image', models.ImageField(blank=True, upload_to='review')),
                ('content', models.TextField()),
                ('stars', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='SheltradeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='Thsi is for shltrade phone numbers and emails', max_length=50)),
                ('contact_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Sheltrade Contact',
                'verbose_name_plural': 'Sheltrade Contacts',
            },
        ),
        migrations.CreateModel(
            name='SheltradeSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=50)),
                ('social_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Sheltrade Social Media',
                'verbose_name_plural': 'Sheltrade Social Medias',
            },
        ),
    ]
