# Generated by Django 5.1.2 on 2025-05-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_review_sheltradecontact_sheltradesocialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default1.png', upload_to='review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(default=[1, 2, 3, 4, 5]),
        ),
    ]
