# Generated by Django 5.1.2 on 2025-05-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_review_image_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheltradecontact',
            name='contact_url',
            field=models.CharField(max_length=200),
        ),
    ]
