# Generated by Django 4.2.21 on 2025-05-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_review_stars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
