# Generated by Django 5.1.2 on 2025-03-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=500)),
                ('currency', models.CharField(help_text='Accepted currency for this account. E.g.: USD, EUR, NGN', max_length=10)),
            ],
            options={
                'verbose_name': 'BankDetail',
                'verbose_name_plural': 'BankDetails',
            },
        ),
        migrations.CreateModel(
            name='CashBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Percentage(%) per transaction for Airtime, Data, Electric bills, Cable bills')),
            ],
            options={
                'verbose_name': 'Cash Back',
                'verbose_name_plural': 'Cash Backs',
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoName', models.CharField(max_length=255)),
                ('walletAddress', models.CharField(max_length=255)),
                ('cryptoSymbol', models.CharField(help_text='E.g.: BTC, ETH, USDT', max_length=10)),
                ('minimumDeposit', models.DecimalField(blank=True, decimal_places=20, help_text='Minimum deposit amount. E.g: 0.00100000 ETH', max_digits=25, null=True)),
            ],
            options={
                'verbose_name': 'CryptoWallet',
                'verbose_name_plural': 'CryptoWallets',
            },
        ),
        migrations.CreateModel(
            name='TransactionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.PositiveIntegerField(help_text='Percentage(%) per transaction for Giftcard, Crypto')),
            ],
            options={
                'verbose_name': 'Transaction Charge',
                'verbose_name_plural': 'Transaction Charges',
            },
        ),
    ]
