# Generated by Django 5.1.2 on 2025-05-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalaccount',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
    ]
