# Generated by Django 5.1.2 on 2025-03-22 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositnarations',
            options={'verbose_name': 'Deposit Naration', 'verbose_name_plural': 'Deposit Narations'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalaccount',
            options={'verbose_name': 'Withdrawal Account', 'verbose_name_plural': 'Withdrawal Accounts'},
        ),
        migrations.CreateModel(
            name='CashBackEarned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_back_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Back Earned',
                'verbose_name_plural': 'Cash Backs Earned',
            },
        ),
    ]
