# Generated by Django 5.1.2 on 2025-05-25 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('card_type', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('card_pin', models.CharField(max_length=255)),
                ('card_code', models.CharField(max_length=255)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(max_length=255)),
                ('restrictions', models.TextField(blank=True)),
                ('uploaded_image', models.ImageField(blank=True, default='defaults/gift-card.png', null=True, upload_to='giftcards/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
