# Generated by Django 5.1.2 on 2025-03-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(help_text='Brand/retailer name e.g., Amazon, Steam', max_length=50)),
                ('card_number', models.CharField(blank=True, help_text='Unique number on the gift card (if applicable).', max_length=30, null=True)),
                ('card_pin', models.CharField(blank=True, help_text='PIN code required for redemption (if applicable).', max_length=30, null=True)),
                ('card_code', models.CharField(blank=True, help_text='Additional redemption code (if required).', max_length=20, null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Expiration date of the gift card, if applicable.', null=True)),
                ('condition', models.CharField(blank=True, help_text='Condition of the gift card (e.g., new, used, partially used).', max_length=20, null=True)),
                ('restrictions', models.TextField(blank=True, help_text='Any specific terms or restrictions related to this card.', null=True)),
                ('uploaded_image', models.ImageField(blank=True, default='media/defaults/gift-card.png', help_text='Optional: Image of the physical or digital gift card.', null=True, upload_to='media/gift_cards/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='The price at which the seller lists this gift card.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('invalid', 'Invalid'), ('listed', 'Listed for Sale'), ('sold', 'Sold')], db_index=True, default='pending', help_text='Current status of the gift card (e.g., pending, invalid, listed, sold).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the gift card was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the gift card details were last updated.')),
                ('seller', models.ForeignKey(help_text='The user who owns and is selling this gift card.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyGiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_status', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded')], default='held', help_text='Current escrow status of the transaction (held, released, refunded).', max_length=10)),
                ('bought_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the gift card was purchased.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the transaction details were last updated.')),
                ('buyer', models.ForeignKey(help_text='The user who purchased the gift card.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_cards', to=settings.AUTH_USER_MODEL)),
                ('gift_card', models.ForeignKey(help_text='Reference to the purchased gift card.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought', to='giftcard.giftcard')),
            ],
        ),
    ]
