# Generated by Django 5.1.2 on 2025-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
