# Generated by Django 5.1.2 on 2025-05-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='uploaded_image',
            field=models.ImageField(blank=True, default='defaults/gift-card.png', null=True, upload_to='giftcards/'),
        ),
    ]
