# Generated by Django 4.2.23 on 2025-07-11 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftcard', '0002_alter_giftcard_condition_alter_giftcard_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_giftcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Verification'), ('listed', 'Listed for Sale'), ('Sold', 'Sold'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
