# Generated by Django 5.1.2 on 2025-05-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0002_alter_giftcard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
