# Generated by Django 4.2.21 on 2025-05-17 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftcard', '0002_alter_giftcard_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='buyer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_buyer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcard',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BuyGiftCard',
        ),
    ]
