# Generated by Django 5.1.2 on 2025-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0003_giftcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Listed', 'Listed'), ('Sold', 'Sold'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
