# Generated by Django 5.1.2 on 2025-05-25 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTransactionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='The saved phone number associated with the transaction.', max_length=150)),
                ('provider', models.CharField(help_text='The service provider associated with this phone number (e.g., MTN, Glo, Airtel).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this transaction info was saved.')),
                ('user', models.ForeignKey(help_text='The user to whom this transaction info belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Transaction Info',
                'verbose_name_plural': 'Saved Transaction Infos',
                'ordering': ['-created_at'],
            },
        ),
    ]
