# Generated by Django 5.1.2 on 2025-03-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkersActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workersAction', models.CharField(help_text="Description of the worker's action.", max_length=150, verbose_name="Worker's Actions")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this activity was recorded.')),
                ('worker', models.ForeignKey(help_text='The worker responsible for this activity.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Worker's Activity",
                'verbose_name_plural': "Worker's Activities",
                'ordering': ['-created_at'],
            },
        ),
    ]
