# Generated by Django 5.1.2 on 2025-03-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(help_text='The name of the cryptocurrency (e.g., Bitcoin, Ethereum).', max_length=255)),
                ('address', models.CharField(help_text='The wallet address associated with the specified cryptocurrency.', max_length=255)),
                ('user', models.ForeignKey(help_text='The user who owns this cryptocurrency address.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-id'],
            },
        ),
    ]
